### ISSUE TITLE
How many the training samples and the test samples and why not comapred with other sota models?

### ISSUE THREAD

**Issue by Layne-Huang** [divelab/GraphBP#10]
Hi,

I have noticed that the dataset consists of 500K samples after filtering which is described in your paper. However, the it2_tt_0_lowrmsd_mols_test0_fixed.types file includes more than 480K samples while it2_tt_0_lowrmsd_mols_test0_fixed.types file includes more than 230K samples. 

You have selected 10 target proteins as LiGAN for test evaluation, but 90 protein-ligand pairs in the test set as reference. Does it mean that generated 100 samples for each target protein would be compared with these pairs?

Could you please tell me how many training samples can obtain the results in your paper?

Besides, why did you not compare the model with Luo's model (Luo, S., Guan, J., Ma, J., and Peng, J. A 3d generative model for structure-based drug design. In Thirty-Fifth Conference on Neural Information Processing Systems, 2021a), which you mentioned in the related works?

Thank you very much!

**Comment by mengliu1998** [comment]
@Layne-Huang，

Hi, thanks for your interest.

Yes, the number of training samples is around 500k. The training samples are summarized in [it2_tt_0_lowrmsd_mols_train0_fixed.types](https://github.com/divelab/GraphBP/blob/main/GraphBP/data/crossdock2020/it2_tt_0_lowrmsd_mols_train0_fixed.types).

For evaluation, the reference protein-ligand pairs are selected based on [selected_test_targets.types](https://github.com/mattragoza/LiGAN/blob/master/data/crossdock2020/selected_test_targets.types). These 90 pairs include 10 different target proteins. Then, for each reference pair, we generate 100 samples and compare them to the corresponding reference. In other words, we generate 9000 ligand molecules.

We did not compare with Luo et al., 2021 since it code is not fully available when we submitted this work. In addition, the evaluation setup between LiGAN and Luo et al., 2021 are different. For simplicity, we followed the LiGAN setup.

Hope this helps. Thank you!
